### ISSUE TITLE
Student Attendance Report

### ISSUE THREAD

**Issue by verma6uc** [ISTARSkills/tfy_orgadmin#14]
This report will contains following columns.
user_id | user_name | college_name | group name | total classes | attendance count  
This report will come under super admin.
This task involves development and testing by developer.

**Comment by Sumanth-istar** [comment]
query has been written
doing Testing

**Comment by Sumanth-istar** [comment]
SELECT
	T1.user_id,
	T1.first_name,
	T1.col_name,
	T1.bg_name,
	T1.tot_event,
	T4.PRESENT
FROM
	(
		SELECT DISTINCT
			user_profile.user_id,
			user_profile.first_name,
			batch_group. ID AS bg_id,
			batch_group. NAME AS bg_name,
			organization. NAME AS col_name,
			COUNT (
				batch_schedule_event.batch_group_code
			) AS tot_event
		FROM
			batch_schedule_event,
			user_profile,
			batch_group,
			organization
		WHERE
			batch_schedule_event. TYPE = 'BATCH_SCHEDULE_EVENT_STUDENT'
		AND batch_schedule_event.actor_id = user_profile.user_id
		AND batch_group. ID = batch_schedule_event.batch_group_id
		AND organization. ID = batch_group.college_id
		AND organization. ID != 2
		GROUP BY
			user_profile.user_id,
			user_profile.first_name,
			bg_id,
			batch_group. NAME,
			organization. NAME
		ORDER BY
			batch_group. ID
	) T1
LEFT JOIN (
	SELECT
		t3.actor_id,
		t3.batch_group_id,
		COUNT (attendance. ID) FILTER (

			WHERE
				attendance.status = 'PRESENT'
		) AS PRESENT
	FROM
		(
			SELECT DISTINCT
				T2.*, batch_schedule_event. ID
			FROM
				(
					SELECT DISTINCT
						batch_schedule_event.actor_id,
						batch_schedule_event.batch_group_id,
						batch_schedule_event.batch_group_code
					FROM
						batch_schedule_event,
						user_profile,
						batch_group,
						organization
					WHERE
						batch_schedule_event. TYPE = 'BATCH_SCHEDULE_EVENT_STUDENT'
					AND batch_schedule_event.actor_id = user_profile.user_id
					AND batch_group. ID = batch_schedule_event.batch_group_id
					AND organization. ID = batch_group.college_id
					AND organization. ID != 2
					ORDER BY
						batch_schedule_event.actor_id
				) T2
			LEFT JOIN batch_schedule_event ON (
				T2.batch_group_code = batch_schedule_event.batch_group_code
				AND batch_schedule_event. TYPE = 'BATCH_SCHEDULE_EVENT_TRAINER'
			)
			WHERE
				batch_schedule_event. ID IS NOT NULL
		) T3
	LEFT JOIN attendance ON (
		T3. ID = attendance.event_id
		AND T3.actor_id = attendance.user_id
	)
	GROUP BY
		t3.actor_id,
		t3.batch_group_id
) T4 ON (
	T1.bg_id = T4.batch_group_id
	AND T1.user_id = T4.actor_id
)

**Comment by verma6uc** [comment]
total classes | attendance count

For these two columns total classess will be classes which are in attendance, completed or feedback status in that section.
and attendance count is in how many he was present.

**Comment by Sumanth-istar** [comment]
SELECT DISTINCT
	T1.user_id,
	T1.first_name,
	T1.col_name,
	T1.bg_name,
	T4.PRESENT,
	T5.total_event
FROM
	(
		SELECT DISTINCT
			user_profile.user_id,
			user_profile.first_name,
			batch_group. ID AS bg_id,
			batch_group. NAME AS bg_name,
			organization. NAME AS col_name
		FROM
			batch_schedule_event,
			user_profile,
			batch_group,
			organization
		WHERE
			batch_schedule_event. TYPE = 'BATCH_SCHEDULE_EVENT_STUDENT'
		AND batch_schedule_event.actor_id = user_profile.user_id
		AND batch_group. ID = batch_schedule_event.batch_group_id
		AND organization. ID = batch_group.college_id
		AND organization. ID != 2
		GROUP BY
			user_profile.user_id,
			user_profile.first_name,
			bg_id,
			batch_group. NAME,
			organization. NAME
		ORDER BY
			batch_group. ID
	) T1
LEFT JOIN (
	SELECT
		t3.actor_id,
		t3.batch_group_id,
		COUNT (attendance. ID) FILTER (

			WHERE
				attendance.status = 'PRESENT'
		) AS PRESENT,
		COUNT (DISTINCT attendance. ID) AS total_attendance
	FROM
		(
			SELECT DISTINCT
				T2.*, batch_schedule_event. ID
			FROM
				(
					SELECT DISTINCT
						batch_schedule_event.actor_id,
						batch_schedule_event.batch_group_id,
						batch_schedule_event.batch_group_code
					FROM
						batch_schedule_event,
						user_profile,
						batch_group,
						organization
					WHERE
						batch_schedule_event. TYPE = 'BATCH_SCHEDULE_EVENT_STUDENT'
					AND batch_schedule_event.actor_id = user_profile.user_id
					AND batch_group. ID = batch_schedule_event.batch_group_id
					AND organization. ID = batch_group.college_id
					AND organization. ID != 2
					ORDER BY
						batch_schedule_event.actor_id
				) T2
			LEFT JOIN batch_schedule_event ON (
				T2.batch_group_code = batch_schedule_event.batch_group_code
				AND batch_schedule_event. TYPE = 'BATCH_SCHEDULE_EVENT_TRAINER'
			)
			WHERE
				batch_schedule_event. ID IS NOT NULL
		) T3
	LEFT JOIN attendance ON (
		T3. ID = attendance.event_id
		AND T3.actor_id = attendance.user_id
	)
	GROUP BY
		t3.actor_id,
		t3.batch_group_id
) T4 ON (
	T1.bg_id = T4.batch_group_id
	AND T1.user_id = T4.actor_id
)
LEFT JOIN (
	SELECT DISTINCT
		t2.actor_id,
		t2.batch_group_id,
		COUNT (batch_schedule_event. ID) FILTER (

			WHERE
				batch_schedule_event.status != 'SCHEDULED'
		) AS total_event
	FROM
		(
			SELECT DISTINCT
				batch_schedule_event.actor_id,
				batch_schedule_event.batch_group_id,
				batch_schedule_event.batch_group_code
			FROM
				batch_schedule_event,
				user_profile,
				batch_group,
				organization
			WHERE
				batch_schedule_event. TYPE = 'BATCH_SCHEDULE_EVENT_STUDENT'
			AND batch_schedule_event.actor_id = user_profile.user_id
			AND batch_group. ID = batch_schedule_event.batch_group_id
			AND organization. ID = batch_group.college_id
			AND organization. ID != 2
			ORDER BY
				batch_schedule_event.actor_id
		) T2
	LEFT JOIN batch_schedule_event ON (
		T2.batch_group_code = batch_schedule_event.batch_group_code
		AND batch_schedule_event. TYPE = 'BATCH_SCHEDULE_EVENT_TRAINER'
	)
	WHERE
		batch_schedule_event. ID IS NOT NULL
	GROUP BY
		t2.actor_id,
		t2.batch_group_id
) T5 ON (
	T1.bg_id = T5.batch_group_id
	AND T1.user_id = T5.actor_id
)
