### ISSUE TITLE
Daily Event Summary

### ISSUE THREAD

**Issue by verma6uc** [ISTARSkills/tfy_orgadmin#15]
This report contains following columns

Organization,	Course name,	section name,	Trainer,	scheduled date and time, tot_happened_or_not,	when session was actually started, when session actually ended,	duration of session, 	student enrolled	attendance (25/58),	sessions covered(comma seperated list of session name with session id in brackets),	Trainer Comments,	Trainer rating,	Avg rating of student , noise, attendance rating, sick rating, content, assignment, internals, internet, electricity, time, projector.

This task involves dev and testing by developer.

**Comment by Sumanth-istar** [comment]
SELECT
	TF1.*, CASE
WHEN
	COUNT (
		DISTINCT batch_schedule_event. ID
	) != 0 THEN
		'true'
	ELSE
		'false'
	END AS tot_happened
	FROM
		(
			SELECT
				T1.*, CAST (
					COALESCE (
						to_char(
							MIN (
								slide_change_log.created_at
							),
							'DD-Mon-yyyy HH24:MI'
						),
						'N/A'
					) AS VARCHAR
				) AS session_started,
				CAST (
					COALESCE (
						to_char(
							MAX (
								slide_change_log.created_at
							),
							'DD-Mon-yyyy HH24:MI'
						),
						'N/A'
					) AS VARCHAR
				) AS session_ended,
				COUNT (DISTINCT attendance. ID) FILTER (

					WHERE
						attendance.status = 'PRESENT'
				) AS total_attendance_count,
				CASE
			WHEN trainer_feedback.comments IS NULL
			OR trainer_feedback.comments = '' THEN
				'N/A'
			ELSE
				trainer_feedback.comments
			END AS trainer_comment,
			COALESCE (
				CAST (
					trainer_feedback.rating AS VARCHAR
				),
				'N/A'
			) AS trainer_rating,
			COALESCE (
				CAST (
					AVG (student_feedback.rating) AS VARCHAR
				),
				'N/A'
			) AS avg_student_rating,
			COALESCE (
				string_agg (
					DISTINCT cmsession.title || '(' || cmsession. ID || ')',
					', '
				),
				'N/A'
			) AS session_covered
		FROM
			(
				SELECT DISTINCT
					batch_schedule_event. ID AS event_id,
					organization. NAME AS college_name,
					course. ID AS course_id,
					course.course_name AS course_name,
					batch_group. NAME AS batch_group_name,
					user_profile.user_id AS user_id,
					user_profile.first_name AS t_name,
					batch_schedule_event.eventhour * 60 + batch_schedule_event.eventminute AS total_duration,
					to_char(
						batch_schedule_event.eventdate,
						'DD-Mon-yyyy HH24:MI'
					) AS event_date,
					COUNT (
						DISTINCT batch_students.student_id
					) AS student_enrolled
				FROM
					batch_schedule_event,
					classroom_details,
					organization,
					course,
					batch_group,
					batch_students,
					user_profile
				WHERE
					batch_schedule_event.classroom_id = classroom_details. ID
				AND classroom_details.organization_id = organization. ID
				AND batch_schedule_event.course_id = course. ID
				AND batch_group. ID = batch_schedule_event.batch_group_id
				AND batch_group. ID = batch_students.batch_group_id
				AND user_profile.user_id = batch_schedule_event.actor_id
				AND batch_schedule_event. TYPE = 'BATCH_SCHEDULE_EVENT_TRAINER'
				AND organization. ID != 2
				GROUP BY
					organization. NAME,
					course.course_name,
					batch_group. NAME,
					batch_schedule_event. ID,
					batch_schedule_event.eventdate,
					total_duration,
					user_profile.first_name,
					user_id,
					course. ID
			) T1
		LEFT JOIN slide_change_log ON (
			slide_change_log.event_id = T1.event_id
		)
		LEFT JOIN attendance ON (
			attendance.event_id = T1.event_id
		)
		LEFT JOIN trainer_feedback ON (
			T1.event_id = trainer_feedback.event_id
		)
		LEFT JOIN cmsession ON (
			slide_change_log.cmsession_id = cmsession. ID
		)
		LEFT JOIN student_feedback ON (
			T1.event_id = student_feedback.event_id
		)
		GROUP BY
			T1.college_name,
			T1.course_name,
			T1.batch_group_name,
			T1.event_id,
			T1.event_date,
			T1.total_duration,
			T1.student_enrolled,
			T1.t_name,
			t1.user_id,
			t1.course_id,
			trainer_feedback.comments,
			trainer_feedback.rating
		ORDER BY
			T1.event_date
		) TF1
	LEFT JOIN batch_schedule_event ON (
		TF1.course_id = batch_schedule_event.course_id
		AND TF1.user_id = batch_schedule_event.actor_id
		AND batch_schedule_event. TYPE = 'BATCH_SCHEDULE_EVENT_STUDENT'
	)
	GROUP BY
		TF1.college_name,
		TF1.course_name,
		TF1.batch_group_name,
		TF1.event_id,
		TF1.event_date,
		TF1.total_duration,
		TF1.student_enrolled,
		TF1.t_name,
		TF1.user_id,
		TF1.course_id,
		TF1.trainer_comment,
		TF1.trainer_rating,
		tf1.session_started,
		tf1.session_ended,
		tf1.total_attendance_count,
		tf1.avg_student_rating,
		tf1.session_covered

**Comment by Sumanth-istar** [comment]
SELECT
	TF1.college_name,
	TF1.course_name,
	TF1.batch_group_name,
	TF1.event_date,
	TF1.total_duration,
	TF1.student_enrolled,
	TF1.t_name,
	TF1.trainer_comment,
	TF1.trainer_rating,
	tf1.session_started,
	tf1.session_ended,
	tf1.total_attendance_count,
	tf1.avg_student_rating,
	tf1.session_covered,
	tf1.noise,
	tf1.attendance,
	tf1.sick,
	tf1. CONTENT,
	tf1. ASSIGNMENT,
	tf1.internals,
	tf1.internet,
	tf1.electricity,
	tf1. TIME,
	tf1.projector,
	CASE
WHEN COUNT (
	DISTINCT batch_schedule_event. ID
) != 0 THEN
	'true'
ELSE
	'false'
END AS tot_happened
FROM
	(
		SELECT
			T1.*, CAST (
				COALESCE (
					to_char(
						MIN (
							slide_change_log.created_at
						),
						'DD-Mon-yyyy HH24:MI'
					),
					'N/A'
				) AS VARCHAR
			) AS session_started,
			CAST (
				COALESCE (
					to_char(
						MAX (
							slide_change_log.created_at
						),
						'DD-Mon-yyyy HH24:MI'
					),
					'N/A'
				) AS VARCHAR
			) AS session_ended,
			COUNT (DISTINCT attendance. ID) FILTER (

				WHERE
					attendance.status = 'PRESENT'
			) AS total_attendance_count,
			CASE
		WHEN trainer_feedback.comments IS NULL
		OR trainer_feedback.comments = '' THEN
			'N/A'
		ELSE
			trainer_feedback.comments
		END AS trainer_comment,
		COALESCE (
			CAST (
				trainer_feedback.rating AS VARCHAR
			),
			'N/A'
		) AS trainer_rating,
		COALESCE (
			CAST (
				trainer_feedback.noise AS VARCHAR
			),
			'N/A'
		) AS noise,
		COALESCE (
			CAST (
				trainer_feedback.attendance AS VARCHAR
			),
			'N/A'
		) AS attendance,
		COALESCE (
			CAST (
				trainer_feedback.sick AS VARCHAR
			),
			'N/A'
		) AS sick,
		COALESCE (
			CAST (
				trainer_feedback. CONTENT AS VARCHAR
			),
			'N/A'
		) AS CONTENT,
		COALESCE (
			CAST (
				trainer_feedback. ASSIGNMENT AS VARCHAR
			),
			'N/A'
		) AS ASSIGNMENT,
		COALESCE (
			CAST (
				trainer_feedback.internals AS VARCHAR
			),
			'N/A'
		) AS internals,
		COALESCE (
			CAST (
				trainer_feedback.internet AS VARCHAR
			),
			'N/A'
		) AS internet,
		COALESCE (
			CAST (
				trainer_feedback.electricity AS VARCHAR
			),
			'N/A'
		) AS electricity,
		COALESCE (
			CAST (
				trainer_feedback. TIME AS VARCHAR
			),
			'N/A'
		) AS TIME,
		COALESCE (
			CAST (
				trainer_feedback.projector AS VARCHAR
			),
			'N/A'
		) AS projector,
		COALESCE (
			CAST (
				AVG (student_feedback.rating) AS VARCHAR
			),
			'N/A'
		) AS avg_student_rating,
		COALESCE (
			string_agg (
				DISTINCT cmsession.title || '(' || cmsession. ID || ')',
				', &lt;br&gt;'
			),
			'N/A'
		) AS session_covered
	FROM
		(
			SELECT DISTINCT
				batch_schedule_event. ID AS event_id,
				organization. NAME AS college_name,
				course. ID AS course_id,
				course.course_name AS course_name,
				batch_group. NAME AS batch_group_name,
				user_profile.user_id AS user_id,
				user_profile.first_name AS t_name,
				batch_schedule_event.eventhour * 60 + batch_schedule_event.eventminute AS total_duration,
				to_char(
					batch_schedule_event.eventdate,
					'DD-Mon-yyyy HH24:MI'
				) AS event_date,
				COUNT (
					DISTINCT batch_students.student_id
				) AS student_enrolled
			FROM
				batch_schedule_event,
				classroom_details,
				organization,
				course,
				batch_group,
				batch_students,
				user_profile
			WHERE
				batch_schedule_event.classroom_id = classroom_details. ID
			AND classroom_details.organization_id = organization. ID
			AND batch_schedule_event.course_id = course. ID
			AND batch_group. ID = batch_schedule_event.batch_group_id
			AND batch_group. ID = batch_students.batch_group_id
			AND user_profile.user_id = batch_schedule_event.actor_id
			AND batch_schedule_event. TYPE = 'BATCH_SCHEDULE_EVENT_TRAINER'
			AND organization. ID != 2
			GROUP BY
				organization. NAME,
				course.course_name,
				batch_group. NAME,
				batch_schedule_event. ID,
				batch_schedule_event.eventdate,
				total_duration,
				user_profile.first_name,
				user_id,
				course. ID
		) T1
	LEFT JOIN slide_change_log ON (
		slide_change_log.event_id = T1.event_id
	)
	LEFT JOIN attendance ON (
		attendance.event_id = T1.event_id
	)
	LEFT JOIN trainer_feedback ON (
		T1.event_id = trainer_feedback.event_id
	)
	LEFT JOIN cmsession ON (
		slide_change_log.cmsession_id = cmsession. ID
	)
	LEFT JOIN student_feedback ON (
		T1.event_id = student_feedback.event_id
	)
	GROUP BY
		T1.college_name,
		T1.course_name,
		T1.batch_group_name,
		T1.event_id,
		T1.event_date,
		T1.total_duration,
		T1.student_enrolled,
		T1.t_name,
		t1.user_id,
		t1.course_id,
		trainer_feedback.comments,
		trainer_feedback.rating,
		trainer_feedback.noise,
		trainer_feedback.attendance,
		trainer_feedback.sick,
		trainer_feedback. CONTENT,
		trainer_feedback. ASSIGNMENT,
		trainer_feedback.internals,
		trainer_feedback.internet,
		trainer_feedback.electricity,
		trainer_feedback. TIME,
		trainer_feedback.projector
	ORDER BY
		T1.event_date
	) TF1
LEFT JOIN batch_schedule_event ON (
	TF1.course_id = batch_schedule_event.course_id
	AND TF1.user_id = batch_schedule_event.actor_id
	AND batch_schedule_event. TYPE = 'BATCH_SCHEDULE_EVENT_STUDENT'
)
GROUP BY
	TF1.college_name,
	TF1.course_name,
	TF1.batch_group_name,
	TF1.event_id,
	TF1.event_date,
	TF1.total_duration,
	TF1.student_enrolled,
	TF1.t_name,
	TF1.user_id,
	TF1.course_id,
	TF1.trainer_comment,
	TF1.trainer_rating,
	tf1.session_started,
	tf1.session_ended,
	tf1.total_attendance_count,
	tf1.avg_student_rating,
	tf1.session_covered,
	tf1.noise,
	tf1.attendance,
	tf1.sick,
	tf1. CONTENT,
	tf1. ASSIGNMENT,
	tf1.internals,
	tf1.internet,
	tf1.electricity,
	tf1. TIME,
	tf1.projector

**Comment by Sumanth-istar** [comment]
SELECT
TF1.college_name,
TF1.course_name,
TF1.batch_group_name,
TF1.event_date,
round(
	CAST (
		SUM (
			TF1.total_duration
		) / CAST ('60' AS FLOAT) AS NUMERIC
	),
	2
)AS total_duration,
TF1.student_enrolled,
TF1.t_name,
TF1.trainer_comment,
TF1.trainer_rating,
tf1.session_started,
tf1.session_ended,
tf1.total_attendance_count,
tf1.avg_student_rating,
tf1.session_covered,
tf1.noise,
tf1.attendance,
tf1.sick,
tf1. CONTENT,
tf1. ASSIGNMENT,
tf1.internals,
tf1.internet,
tf1.electricity,
tf1. TIME,
tf1.projector,
CASE
WHEN COUNT (
DISTINCT batch_schedule_event. ID
) != 0 THEN
'true'
ELSE
'false'
END AS tot_happened
FROM
(
SELECT
T1.*, CAST (
COALESCE (
to_char(
MIN (
slide_change_log.created_at
),
'DD-Mon-yyyy HH24:MI'
),
'N/A'
) AS VARCHAR
) AS session_started,
CAST (
COALESCE (
to_char(
MAX (
slide_change_log.created_at
),
'DD-Mon-yyyy HH24:MI'
),
'N/A'
) AS VARCHAR
) AS session_ended,
COUNT (DISTINCT attendance. ID) FILTER (

            WHERE
                attendance.status = 'PRESENT'
        ) AS total_attendance_count,
        CASE
    WHEN trainer_feedback.comments IS NULL
    OR trainer_feedback.comments = '' THEN
        'N/A'
    ELSE
        trainer_feedback.comments
    END AS trainer_comment,
    COALESCE (
        CAST (
            trainer_feedback.rating AS VARCHAR
        ),
        'N/A'
    ) AS trainer_rating,
    COALESCE (
        CAST (
            trainer_feedback.noise AS VARCHAR
        ),
        'N/A'
    ) AS noise,
    COALESCE (
        CAST (
            trainer_feedback.attendance AS VARCHAR
        ),
        'N/A'
    ) AS attendance,
    COALESCE (
        CAST (
            trainer_feedback.sick AS VARCHAR
        ),
        'N/A'
    ) AS sick,
    COALESCE (
        CAST (
            trainer_feedback. CONTENT AS VARCHAR
        ),
        'N/A'
    ) AS CONTENT,
    COALESCE (
        CAST (
            trainer_feedback. ASSIGNMENT AS VARCHAR
        ),
        'N/A'
    ) AS ASSIGNMENT,
    COALESCE (
        CAST (
            trainer_feedback.internals AS VARCHAR
        ),
        'N/A'
    ) AS internals,
    COALESCE (
        CAST (
            trainer_feedback.internet AS VARCHAR
        ),
        'N/A'
    ) AS internet,
    COALESCE (
        CAST (
            trainer_feedback.electricity AS VARCHAR
        ),
        'N/A'
    ) AS electricity,
    COALESCE (
        CAST (
            trainer_feedback. TIME AS VARCHAR
        ),
        'N/A'
    ) AS TIME,
    COALESCE (
        CAST (
            trainer_feedback.projector AS VARCHAR
        ),
        'N/A'
    ) AS projector,
    COALESCE (
        CAST (
            AVG (student_feedback.rating) AS VARCHAR
        ),
        'N/A'
    ) AS avg_student_rating,
    COALESCE (
        string_agg (
            DISTINCT cmsession.title || '(' || cmsession. ID || ')',
            ', &lt;br&gt;'
        ),
        'N/A'
    ) AS session_covered
FROM
    (
        SELECT DISTINCT
            batch_schedule_event. ID AS event_id,
            organization. NAME AS college_name,
            course. ID AS course_id,
            course.course_name AS course_name,
            batch_group. NAME AS batch_group_name,
            user_profile.user_id AS user_id,
            user_profile.first_name AS t_name,
 

           batch_schedule_event.eventhour * 60 + batch_schedule_event.eventminute AS total_duration,
            to_char(
                batch_schedule_event.eventdate,
                'DD-Mon-yyyy HH24:MI'
            ) AS event_date,
            COUNT (
                DISTINCT batch_students.student_id
            ) AS student_enrolled
        FROM
            batch_schedule_event,
            classroom_details,
            organization,
            course,
            batch_group,
            batch_students,
            user_profile
        WHERE
            batch_schedule_event.classroom_id = classroom_details. ID
        AND classroom_details.organization_id = organization. ID
        AND batch_schedule_event.course_id = course. ID
        AND batch_group. ID = batch_schedule_event.batch_group_id
        AND batch_group. ID = batch_students.batch_group_id
        AND user_profile.user_id = batch_schedule_event.actor_id
        AND batch_schedule_event. TYPE = 'BATCH_SCHEDULE_EVENT_TRAINER'
        AND organization. ID != 2
        GROUP BY
            organization. NAME,
            course.course_name,
            batch_group. NAME,
            batch_schedule_event. ID,
            batch_schedule_event.eventdate,
            total_duration,
            user_profile.first_name,
            user_id,
            course. ID
    ) T1
LEFT JOIN slide_change_log ON (
    slide_change_log.event_id = T1.event_id
)
LEFT JOIN attendance ON (
    attendance.event_id = T1.event_id
)
LEFT JOIN trainer_feedback ON (
    T1.event_id = trainer_feedback.event_id
)
LEFT JOIN cmsession ON (
    slide_change_log.cmsession_id = cmsession. ID
)
LEFT JOIN student_feedback ON (
    T1.event_id = student_feedback.event_id
)
GROUP BY
    T1.college_name,
    T1.course_name,
    T1.batch_group_name,
    T1.event_id,
    T1.event_date,
   t1.total_duration,
    T1.student_enrolled,
    T1.t_name,
    t1.user_id,
    t1.course_id,
    trainer_feedback.comments,
    trainer_feedback.rating,
    trainer_feedback.noise,
    trainer_feedback.attendance,
    trainer_feedback.sick,
    trainer_feedback. CONTENT,
    trainer_feedback. ASSIGNMENT,
    trainer_feedback.internals,
    trainer_feedback.internet,
    trainer_feedback.electricity,
    trainer_feedback. TIME,
    trainer_feedback.projector
ORDER BY
    T1.event_date
) TF1

LEFT JOIN batch_schedule_event ON (
TF1.course_id = batch_schedule_event.course_id
AND TF1.user_id = batch_schedule_event.actor_id
AND batch_schedule_event. TYPE = 'BATCH_SCHEDULE_EVENT_STUDENT'
)
GROUP BY
TF1.college_name,
TF1.course_name,
TF1.batch_group_name,
TF1.event_id,
TF1.event_date,
TF1.total_duration,
TF1.student_enrolled,
TF1.t_name,
TF1.user_id,
TF1.course_id,
TF1.trainer_comment,
TF1.trainer_rating,
tf1.session_started,
tf1.session_ended,
tf1.total_attendance_count,
tf1.avg_student_rating,
tf1.session_covered,
tf1.noise,
tf1.attendance,
tf1.sick,
tf1. CONTENT,
tf1. ASSIGNMENT,
tf1.internals,
tf1.internet,
tf1.electricity,
tf1. TIME,
tf1.projector

**Comment by Sumanth-istar** [comment]
SELECT
TF1.college_name,
TF1.course_name,
TF1.batch_group_name,
TF1.event_date,
round(
	CAST (
		SUM (
			TF1.total_duration
		) / CAST ('60' AS FLOAT) AS NUMERIC
	),
	2
)AS total_duration,
TF1.student_enrolled,
TF1.t_name,
TF1.trainer_comment,
TF1.trainer_rating,
tf1.session_started,
tf1.session_ended,
tf1.total_attendance_count,
tf1.avg_student_rating,
tf1.session_covered,
tf1.noise,
tf1.attendance,
tf1.sick,
tf1. CONTENT,
tf1. ASSIGNMENT,
tf1.internals,
tf1.internet,
tf1.electricity,
tf1. TIME,
tf1.projector,
CASE
WHEN COUNT (
DISTINCT batch_schedule_event. ID
) != 0 THEN
'true'
ELSE
'false'
END AS tot_happened
FROM
(
SELECT
T1.*, CAST (
COALESCE (
to_char(
MIN (
slide_change_log.created_at
),
'DD-Mon-yyyy HH24:MI'
),
'N/A'
) AS VARCHAR
) AS session_started,
CAST (
COALESCE (
to_char(
MAX (
slide_change_log.created_at
),
'DD-Mon-yyyy HH24:MI'
),
'N/A'
) AS VARCHAR
) AS session_ended,
COUNT (DISTINCT attendance. ID) FILTER (

            WHERE
                attendance.status = 'PRESENT'
        ) AS total_attendance_count,
        CASE
    WHEN trainer_feedback.comments IS NULL
    OR trainer_feedback.comments = '' THEN
        'N/A'
    ELSE
        trainer_feedback.comments
    END AS trainer_comment,
    COALESCE (
        CAST (
            trainer_feedback.rating AS VARCHAR
        ),
        'N/A'
    ) AS trainer_rating,
    COALESCE (
        CAST (
            trainer_feedback.noise AS VARCHAR
        ),
        'N/A'
    ) AS noise,
    COALESCE (
        CAST (
            trainer_feedback.attendance AS VARCHAR
        ),
        'N/A'
    ) AS attendance,
    COALESCE (
        CAST (
            trainer_feedback.sick AS VARCHAR
        ),
        'N/A'
    ) AS sick,
    COALESCE (
        CAST (
            trainer_feedback. CONTENT AS VARCHAR
        ),
        'N/A'
    ) AS CONTENT,
    COALESCE (
        CAST (
            trainer_feedback. ASSIGNMENT AS VARCHAR
        ),
        'N/A'
    ) AS ASSIGNMENT,
    COALESCE (
        CAST (
            trainer_feedback.internals AS VARCHAR
        ),
        'N/A'
    ) AS internals,
    COALESCE (
        CAST (
            trainer_feedback.internet AS VARCHAR
        ),
        'N/A'
    ) AS internet,
    COALESCE (
        CAST (
            trainer_feedback.electricity AS VARCHAR
        ),
        'N/A'
    ) AS electricity,
    COALESCE (
        CAST (
            trainer_feedback. TIME AS VARCHAR
        ),
        'N/A'
    ) AS TIME,
    COALESCE (
        CAST (
            trainer_feedback.projector AS VARCHAR
        ),
        'N/A'
    ) AS projector,
    COALESCE (
        CAST (
            AVG (student_feedback.rating) AS VARCHAR
        ),
        'N/A'
    ) AS avg_student_rating,
    COALESCE (
        string_agg (
            DISTINCT cmsession.title || '(' || cmsession. ID || ')',
            ', &lt;br&gt;'
        ),
        'N/A'
    ) AS session_covered
FROM
    (
        SELECT DISTINCT
            batch_schedule_event. ID AS event_id,
            organization. NAME AS college_name,
            course. ID AS course_id,
            course.course_name AS course_name,
            batch_group. NAME AS batch_group_name,
            user_profile.user_id AS user_id,
            user_profile.first_name AS t_name,
 

           batch_schedule_event.eventhour * 60 + batch_schedule_event.eventminute AS total_duration,
            to_char(
                batch_schedule_event.eventdate,
                'DD-Mon-yyyy HH24:MI'
            ) AS event_date,
            COUNT (
                DISTINCT batch_students.student_id
            ) AS student_enrolled
        FROM
            batch_schedule_event,
            classroom_details,
            organization,
            course,
            batch_group,
            batch_students,
            user_profile
        WHERE
            batch_schedule_event.classroom_id = classroom_details. ID
        AND classroom_details.organization_id = organization. ID
        AND batch_schedule_event.course_id = course. ID
        AND batch_group. ID = batch_schedule_event.batch_group_id
        AND batch_group. ID = batch_students.batch_group_id
        AND user_profile.user_id = batch_schedule_event.actor_id
        AND batch_schedule_event. TYPE = 'BATCH_SCHEDULE_EVENT_TRAINER'
        AND organization. ID != 2
        GROUP BY
            organization. NAME,
            course.course_name,
            batch_group. NAME,
            batch_schedule_event. ID,
            batch_schedule_event.eventdate,
            total_duration,
            user_profile.first_name,
            user_id,
            course. ID
    ) T1
LEFT JOIN slide_change_log ON (
    slide_change_log.event_id = T1.event_id
)
LEFT JOIN attendance ON (
    attendance.event_id = T1.event_id
)
LEFT JOIN trainer_feedback ON (
    T1.event_id = trainer_feedback.event_id
)
LEFT JOIN cmsession ON (
    slide_change_log.cmsession_id = cmsession. ID
)
LEFT JOIN student_feedback ON (
    T1.event_id = student_feedback.event_id
)
GROUP BY
    T1.college_name,
    T1.course_name,
    T1.batch_group_name,
    T1.event_id,
    T1.event_date,
   t1.total_duration,
    T1.student_enrolled,
    T1.t_name,
    t1.user_id,
    t1.course_id,
    trainer_feedback.comments,
    trainer_feedback.rating,
    trainer_feedback.noise,
    trainer_feedback.attendance,
    trainer_feedback.sick,
    trainer_feedback. CONTENT,
    trainer_feedback. ASSIGNMENT,
    trainer_feedback.internals,
    trainer_feedback.internet,
    trainer_feedback.electricity,
    trainer_feedback. TIME,
    trainer_feedback.projector
ORDER BY
    T1.event_date
) TF1

LEFT JOIN batch_schedule_event ON (
TF1.course_id = batch_schedule_event.course_id
AND TF1.user_id = batch_schedule_event.actor_id
AND batch_schedule_event. TYPE = 'BATCH_SCHEDULE_EVENT_STUDENT'
)
GROUP BY
TF1.college_name,
TF1.course_name,
TF1.batch_group_name,
TF1.event_id,
TF1.event_date,
TF1.total_duration,
TF1.student_enrolled,
TF1.t_name,
TF1.user_id,
TF1.course_id,
TF1.trainer_comment,
TF1.trainer_rating,
tf1.session_started,
tf1.session_ended,
tf1.total_attendance_count,
tf1.avg_student_rating,
tf1.session_covered,
tf1.noise,
tf1.attendance,
tf1.sick,
tf1. CONTENT,
tf1. ASSIGNMENT,
tf1.internals,
tf1.internet,
tf1.electricity,
tf1. TIME,
tf1.projector

**Comment by verma6uc** [comment]
this report contains true and false, this can be converted into correct tick and incorrect tick using BOOLEAN_HANDLER.
and where ever rating is mentioned can be converted into stars either using DECIMAL_STAR_RATING or STAR_RATING column handler.
Sample can be seen in report_list.xml in <reports id="3084" type_of_report="table">

**Comment by verma6uc** [comment]
There are two issues here.
One is date selector is causing problem in filtering datatables.
Second is ui is table column width problem.
We need to sit to solve this problem. once u r done with task.
