### ISSUE TITLE
Trainer Compiled Session Report

### ISSUE THREAD

**Issue by verma6uc** [ISTARSkills/tfy_orgadmin#18]
This task contains following columns

trainer id, 	trainer name,	organization name, 	course name,	section name,	classess scheduled,	classes incomplete,	classess pending, 	classess completed,	hours scheduled,	hours incomplete,	hours pending,	hours finished

**Comment by Sumanth-istar** [comment]
SELECT DISTINCT
	user_profile.user_id AS trainer_id,
	user_profile.first_name AS trainer_name,
	organization. NAME AS org_name,
	course.course_name AS course_name,
	batch_group. NAME AS section_name,
	COUNT (
		DISTINCT batch_schedule_event. ID
	) AS classes_scheduled,
	COUNT (
		DISTINCT batch_schedule_event. ID
	) FILTER (

		WHERE
			batch_schedule_event.eventdate < now()
AND batch_schedule_event.status IN ('SCHEDULED', 'TEACHING')
) AS classes_incomplete,
 COUNT (
	DISTINCT batch_schedule_event. ID
) FILTER (

	WHERE
		batch_schedule_event.eventdate <now()
AND batch_schedule_event.status IN (
	'COMPLETED',
	'ATTENDANCE',
	'FEEDBACK'
)
) AS classes_completed,
 COALESCE (
	CAST (
		COUNT (
			DISTINCT batch_schedule_event. ID
		) FILTER (

			WHERE
				batch_schedule_event.eventdate >now()
AND batch_schedule_event.status IN ('SCHEDULED', 'TEACHING')
) AS VARCHAR
),
 'N/A'
) AS classes_pending,
 SUM (
	batch_schedule_event.eventhour * 60 + batch_schedule_event.eventminute
) AS hours_scheduled,
 COALESCE (
	CAST (
		SUM (
			batch_schedule_event.eventhour * 60 + batch_schedule_event.eventminute
		) FILTER (

			WHERE
				batch_schedule_event.eventdate <now()
AND batch_schedule_event.status IN ('SCHEDULED', 'TEACHING')
) AS VARCHAR
),
 'N/A'
) AS hours_incomplete,
 COALESCE (
	CAST (
		SUM (
			batch_schedule_event.eventhour * 60 + batch_schedule_event.eventminute
		) FILTER (

			WHERE
				batch_schedule_event.eventdate <now()
AND batch_schedule_event.status IN (
	'COMPLETED',
	'ATTENDANCE',
	'FEEDBACK'
)
) AS VARCHAR
),
 'N/A'
) AS hours_finished,
 COALESCE (
	CAST (
		SUM (
			batch_schedule_event.eventhour * 60 + batch_schedule_event.eventminute
		) FILTER (

			WHERE
				batch_schedule_event.eventdate >now()
AND batch_schedule_event.status IN ('SCHEDULED', 'TEACHING')
) AS VARCHAR
),
 'N/A'
) AS hours_pending
FROM
	batch_schedule_event,
	user_profile,
	classroom_details,
	organization,
	course,
	batch_group
WHERE
	user_profile.user_id = batch_schedule_event.actor_id
AND classroom_details. ID = batch_schedule_event.classroom_id
AND classroom_details.organization_id = organization. ID
AND course. ID = batch_schedule_event.course_id
AND batch_group. ID = batch_schedule_event.batch_group_id
AND batch_schedule_event. TYPE = 'BATCH_SCHEDULE_EVENT_TRAINER'
GROUP BY
	user_profile.user_id,
	user_profile.first_name,
	organization. NAME,
	course.course_name,
	batch_group. NAME

**Comment by verma6uc** [comment]
hours scheduled, hours finished , hours_incomplete, hours_pending are in min.. need to change them in hours.
Ex 60 min= 1hrs
Ex 30 min = 0.5hrs
Ex 90 min = 1.5hrs

**Comment by Sumanth-istar** [comment]
SELECT DISTINCT
	user_profile.user_id AS trainer_id,
	user_profile.first_name AS trainer_name,
	organization. NAME AS org_name,
	course.course_name AS course_name,
	batch_group. NAME AS section_name,
	COUNT (
		DISTINCT batch_schedule_event. ID
	) AS classes_scheduled,
	COUNT (
		DISTINCT batch_schedule_event. ID
	) FILTER (

		WHERE
			batch_schedule_event.eventdate < now()
		AND batch_schedule_event.status IN ('SCHEDULED', 'TEACHING')
	) AS classes_incomplete,
	COUNT (
		DISTINCT batch_schedule_event. ID
	) FILTER (

		WHERE
			batch_schedule_event.eventdate < now()
		AND batch_schedule_event.status IN (
			'COMPLETED',
			'ATTENDANCE',
			'FEEDBACK'
		)
	) AS classes_completed,
	COALESCE (
		CAST (
			COUNT (
				DISTINCT batch_schedule_event. ID
			) FILTER (

				WHERE
					batch_schedule_event.eventdate > now()
				AND batch_schedule_event.status IN ('SCHEDULED', 'TEACHING')
			) AS VARCHAR
		),
		'N/A'
	) AS classes_pending,
	round(
	CAST (
		SUM (
			batch_schedule_event.eventhour * 60 + batch_schedule_event.eventminute
		) / CAST ('60' AS FLOAT) AS NUMERIC
	),
	2
) AS hours_scheduled,
 COALESCE (
	CAST (
		round(
			CAST (
				(
					(
						SUM (
							batch_schedule_event.eventhour * 60 + batch_schedule_event.eventminute
						) FILTER (

							WHERE
								batch_schedule_event.eventdate <now()
AND batch_schedule_event.status IN ('SCHEDULED', 'TEACHING')
)
) / CAST ('60' AS FLOAT)
) AS NUMERIC
),
 2
) AS VARCHAR
),
 '0'
) AS hours_incomplete,
 COALESCE (
	CAST (
		round(
			CAST (
				(
					(
						SUM (
							batch_schedule_event.eventhour * 60 + batch_schedule_event.eventminute
						) FILTER (

							WHERE
								batch_schedule_event.eventdate <now()
AND batch_schedule_event.status IN (
	'COMPLETED',
	'ATTENDANCE',
	'FEEDBACK'
)
)
) / CAST ('60' AS FLOAT)
) AS NUMERIC
),
 2
) AS VARCHAR
),
 '0'
) AS hours_finished
FROM
	batch_schedule_event,
	user_profile,
	classroom_details,
	organization,
	course,
	batch_group
WHERE
	user_profile.user_id = batch_schedule_event.actor_id
AND classroom_details. ID = batch_schedule_event.classroom_id
AND classroom_details.organization_id = organization. ID
AND course. ID = batch_schedule_event.course_id
AND batch_group. ID = batch_schedule_event.batch_group_id
AND batch_schedule_event. TYPE = 'BATCH_SCHEDULE_EVENT_TRAINER'
GROUP BY
	user_profile.user_id,
	user_profile.first_name,
	organization. NAME,
	course.course_name,
	batch_group. NAME

**Comment by Sumanth-istar** [comment]
SELECT DISTINCT
	user_profile.user_id AS trainer_id,
	user_profile.first_name AS trainer_name,
	organization. NAME AS org_name,
	course.course_name AS course_name,
	batch_group. NAME AS section_name,
	COUNT (
		DISTINCT batch_schedule_event. ID
	) AS classes_scheduled,
	COUNT (
		DISTINCT batch_schedule_event. ID
	) FILTER (

		WHERE
			batch_schedule_event.eventdate < now()
		AND batch_schedule_event.status IN ('SCHEDULED', 'TEACHING')
	) AS classes_incomplete,
	COUNT (
		DISTINCT batch_schedule_event. ID
	) FILTER (

		WHERE
			batch_schedule_event.eventdate < now()
		AND batch_schedule_event.status IN (
			'COMPLETED',
			'ATTENDANCE',
			'FEEDBACK'
		)
	) AS classes_completed,
	COALESCE (
		CAST (
			COUNT (
				DISTINCT batch_schedule_event. ID
			) FILTER (

				WHERE
					batch_schedule_event.eventdate > now()
				AND batch_schedule_event.status IN ('SCHEDULED', 'TEACHING')
			) AS VARCHAR
		),
		'N/A'
	) AS classes_pending,
	round(
		CAST (
			SUM (
				batch_schedule_event.eventhour * 60 + batch_schedule_event.eventminute
			) / CAST ('60' AS FLOAT) AS NUMERIC
		),
		2
	) AS hours_scheduled,
	COALESCE (
		CAST (
			round(
				CAST (
					(
						(
							SUM (
								batch_schedule_event.eventhour * 60 + batch_schedule_event.eventminute
							) FILTER (

								WHERE
									batch_schedule_event.eventdate < now()
								AND batch_schedule_event.status IN ('SCHEDULED', 'TEACHING')
							)
						) / CAST ('60' AS FLOAT)
					) AS NUMERIC
				),
				2
			) AS VARCHAR
		),
		'0'
	) AS hours_incomplete,
	COALESCE (
		CAST (
			round(
				CAST (
					(
						(
							SUM (
								batch_schedule_event.eventhour * 60 + batch_schedule_event.eventminute
							) FILTER (

								WHERE
									batch_schedule_event.eventdate < now()
								AND batch_schedule_event.status IN (
									'COMPLETED',
									'ATTENDANCE',
									'FEEDBACK'
								)
							)
						) / CAST ('60' AS FLOAT)
					) AS NUMERIC
				),
				2
			) AS VARCHAR
		),
		'0'
	) AS hours_finished,
COALESCE (
		CAST (
			round(
				CAST (
					(
						(
							SUM (
								batch_schedule_event.eventhour * 60 + batch_schedule_event.eventminute
							) FILTER (

								WHERE
									batch_schedule_event.eventdate > now()
								AND batch_schedule_event.status IN (
									'SCHEDULED',
									'TEACHING'
									
								)
							)
						) / CAST ('60' AS FLOAT)
					) AS NUMERIC
				),
				2
			) AS VARCHAR
		),
		'0'
	) AS hours_pending
FROM
	batch_schedule_event,
	user_profile,
	classroom_details,
	organization,
	course,
	batch_group
WHERE
	user_profile.user_id = batch_schedule_event.actor_id
AND classroom_details. ID = batch_schedule_event.classroom_id
AND classroom_details.organization_id = organization. ID
AND course. ID = batch_schedule_event.course_id
AND batch_group. ID = batch_schedule_event.batch_group_id
AND batch_schedule_event. TYPE = 'BATCH_SCHEDULE_EVENT_TRAINER'
GROUP BY
	user_profile.user_id,
	user_profile.first_name,
	organization. NAME,
	course.course_name,
	batch_group. NAME
