### ISSUE TITLE
Trainer Compiled TOT and Learning Task

### ISSUE THREAD

**Issue by verma6uc** [ISTARSkills/tfy_orgadmin#19]
This task contains following columns

trainer id,	trainer name,	course name,	lessons scheduled,	lessons incomplete,	lessons pending,	lessons completed, tot happened in this course, how many tot trainer attended.

**Comment by Sumanth-istar** [comment]
SELECT DISTINCT
	t2.user_id,
	t2.trainer_name,
	t2.course_id,
	t2.course_name,
	t2.lessons_scheduled,
	t2.lessons_incomplete,
	t2.lessons_complete,
	t2.lessons_pending, CASE
WHEN COUNT (
	batch_schedule_event.batch_group_code
) > 0 THEN
	'true'
ELSE
	'false'
END AS tot_happened_in_this_course,
 COUNT ( DISTINCT attendance. ID) FILTER (
	WHERE
		attendance.status = 'PRESENT'
	AND attendance.user_id = T2.user_id
) ||'/'||  COUNT ( DISTINCT attendance. ID) FILTER (
	WHERE
	 attendance.user_id = T2.user_id
)  AS total_attendance
FROM
	(
		SELECT DISTINCT
			T1.*, batch_schedule_event.batch_group_code
		FROM
			(
				SELECT DISTINCT
					user_profile.user_id,
					user_profile.first_name AS trainer_name,
					course. ID AS course_id,
					course.course_name,
					COUNT (DISTINCT task. ID) FILTER (

						WHERE
							task.item_type = 'LESSON'
					) AS lessons_scheduled,
					COUNT (DISTINCT task. ID) FILTER (

						WHERE
							task.item_type = 'LESSON'
						AND task.is_active = 'f'
						AND task.start_date < now()
					) AS lessons_incomplete,
					COUNT (DISTINCT task. ID) FILTER (

						WHERE
							task.item_type = 'LESSON'
						AND task.is_active = 't'
						AND task.start_date < now()
					) AS lessons_complete,
					COUNT (task. ID) FILTER (

						WHERE
							task.item_type = 'LESSON'
						AND task.is_active = 'f'
						AND task.start_date > now()
					) AS lessons_pending
				FROM
					task,
					student_playlist,
					user_profile,
					user_role,
					ROLE,
					lesson,
					course
				WHERE
					student_playlist.task_id = task. ID
				AND user_profile.user_id = student_playlist.student_id
				AND user_role.user_id = user_profile.user_id
				AND ROLE . ID = user_role.role_id
				AND ROLE .role_name = 'TRAINER'
				AND task.item_type = 'LESSON'
				AND student_playlist.course_id = course. ID
				GROUP BY
					user_profile.user_id,
					user_profile.first_name,
					course.course_name,
					course. ID
			) T1
		LEFT JOIN batch_schedule_event ON (
			batch_schedule_event.actor_id = T1.user_id
			AND T1.course_id = batch_schedule_event.course_id
			AND batch_schedule_event. TYPE = 'BATCH_SCHEDULE_EVENT_STUDENT'
		)
	) T2
LEFT JOIN batch_schedule_event ON (
	batch_schedule_event.batch_group_code = T2.batch_group_code
	AND T2.course_id = batch_schedule_event.course_id
	AND batch_schedule_event. TYPE = 'BATCH_SCHEDULE_EVENT_TRAINER'
)
LEFT JOIN attendance ON (
	batch_schedule_event. ID = attendance.event_id
)
GROUP BY
	t2.user_id,
	t2.trainer_name,
	t2.course_id,
	t2.course_name,
	t2.lessons_scheduled,
	t2.lessons_incomplete,
	t2.lessons_complete,
	t2.lessons_pending
ORDER BY t2.course_id

**Comment by Sumanth-istar** [comment]
SELECT DISTINCT
	t2.user_id,
	t2.trainer_name,
	t2.course_id,
	t2.course_name,
	t2.lessons_scheduled,
	t2.lessons_incomplete,
	t2.lessons_complete,
	t2.lessons_pending, CASE
WHEN COUNT (
	batch_schedule_event.batch_group_code
) > 0 THEN
	'true'
ELSE
	'false'
END AS tot_happened_in_this_course,
 COUNT ( DISTINCT attendance. ID) FILTER (
	WHERE
		attendance.status = 'PRESENT'
	AND attendance.user_id = T2.user_id
) ||'/'||  COUNT ( DISTINCT batch_schedule_event. ID) AS total_attendance
FROM
	(
		SELECT DISTINCT
			T1.*, batch_schedule_event.batch_group_code
		FROM
			(
				SELECT DISTINCT
					user_profile.user_id,
					user_profile.first_name AS trainer_name,
					course. ID AS course_id,
					course.course_name,
					COUNT (DISTINCT task. ID) FILTER (

						WHERE
							task.item_type = 'LESSON'
					) AS lessons_scheduled,
					COUNT (DISTINCT task. ID) FILTER (

						WHERE
							task.item_type = 'LESSON'
						AND task.is_active = 'f'
						AND task.start_date < now()
					) AS lessons_incomplete,
					COUNT (DISTINCT task. ID) FILTER (

						WHERE
							task.item_type = 'LESSON'
						AND task.is_active = 't'
						AND task.start_date < now()
					) AS lessons_complete,
					COUNT (task. ID) FILTER (

						WHERE
							task.item_type = 'LESSON'
						AND task.is_active = 'f'
						AND task.start_date > now()
					) AS lessons_pending
				FROM
					task,
					student_playlist,
					user_profile,
					user_role,
					ROLE,
					lesson,
					course
				WHERE
					student_playlist.task_id = task. ID
				AND user_profile.user_id = student_playlist.student_id
				AND user_role.user_id = user_profile.user_id
				AND ROLE . ID = user_role.role_id
				AND ROLE .role_name = 'TRAINER'
				AND task.item_type = 'LESSON'
				AND student_playlist.course_id = course. ID
				GROUP BY
					user_profile.user_id,
					user_profile.first_name,
					course.course_name,
					course. ID
			) T1
		LEFT JOIN batch_schedule_event ON (
			batch_schedule_event.actor_id = T1.user_id
			AND T1.course_id = batch_schedule_event.course_id
			AND batch_schedule_event. TYPE = 'BATCH_SCHEDULE_EVENT_STUDENT'
		)
	) T2
LEFT JOIN batch_schedule_event ON (
	batch_schedule_event.batch_group_code = T2.batch_group_code
	AND T2.course_id = batch_schedule_event.course_id
	AND batch_schedule_event. TYPE = 'BATCH_SCHEDULE_EVENT_TRAINER'
)
LEFT JOIN attendance ON (
	batch_schedule_event. ID = attendance.event_id
)
GROUP BY
	t2.user_id,
	t2.trainer_name,
	t2.course_id,
	t2.course_name,
	t2.lessons_scheduled,
	t2.lessons_incomplete,
	t2.lessons_complete,
	t2.lessons_pending
ORDER BY t2.course_id
