### ISSUE TITLE
Trainer Detailed Learning Task Report

### ISSUE THREAD

**Issue by verma6uc** [ISTARSkills/tfy_orgadmin#20]
This task contains following columns

trainer id, 	trainer name,	course name,	module,	session name,	lesson name,	status(completed/incomplete) ,	how many slides covered,	total number of slides.

**Comment by Sumanth-istar** [comment]
SELECT DISTINCT
	t1.user_id,
	t1.first_name,
	t1.course_name,
	t1.module_name,
	t1.cmsession_name,
	t1.lesson_name,
	t1.status, COUNT (
		DISTINCT user_session_log.slide_id
	) AS slide_covered,
	COALESCE (
		user_session_log.total_slide_count,
		0
	) AS total_slide_count
FROM
	(
		SELECT DISTINCT
			user_profile.user_id,
			user_profile.first_name,
			course.course_name AS course_name,
			MODULE .module_name AS module_name,
			cmsession.title AS cmsession_name,
			lesson. ID AS lesson_id,
			lesson.title AS lesson_name,
			student_playlist.status
		FROM
			student_playlist,
			task,
			user_profile,
			course,
			MODULE,
			cmsession,
			lesson
		WHERE
			student_playlist.task_id = task. ID
		AND user_profile.user_id = student_playlist.student_id
		AND course. ID = student_playlist.course_id
		AND MODULE . ID = student_playlist.module_id
		AND cmsession. ID = student_playlist.cmsession_id
		AND lesson. ID = student_playlist.lesson_id
		ORDER BY
			lesson_id
	) T1
LEFT JOIN user_session_log ON (
	T1.user_id = user_session_log.user_id
	AND T1.lesson_id = user_session_log.lesson_id
	AND user_session_log.total_slide_count IS NOT NULL
)
GROUP BY
	t1.user_id,
	t1.first_name,
	t1.course_name,
	t1.module_name,
	t1.cmsession_name,
	t1.lesson_id,
	t1.lesson_name,
	t1.status,
	user_session_log.total_slide_count
ORDER BY t1.user_id
